cn4/urls.py
from django.urls import path, include

from cn4 import views

app_name = 'cn4'

urlpatterns = [
	path('', views.CN4View.as_view()),
]

home/api/urls.py
from django.urls import path

from home.api import views

urlpatterns = [
	path('', views.ApiMainView.as_view(), name='main_api'),
	path('user/', views.UserApiView.as_view(), name='user_api'),
	path('mfa/', views.MFAApiView.as_view(), name='mfa_api'),
	path('journal/', views.JournalApiView.as_view(), name='journal_api'),
	path('weekly_plan/', views.WeeklyPlanApiView.as_view(), name='weekly_plan_api'),
	path('mfa_team/', views.TeamMFAApiView.as_view(), name='team_mfa_api'),
]

home/urls.py
from django.urls import path, include

from home import views

app_name = 'home'

urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('login/', views.LogInView.as_view(), name='login'),
	path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
	path('MFA/', views.MFAView.as_view(), name='MFA'),
	path('MFA_Team/', views.MFA_Team_Selection_View.as_view(), name='MFA_Team'),
	path('logout/', views.user_logout, name='logout'),
	path('profile/', views.ProfileView.as_view(), name='profile'),
	path('teams/', views.TeamsView.as_view(), name='teams'),
	path('B_60/', views.B_60View.as_view(), name='B_60'),
	path('about/', views.AboutView.as_view(), name='about'),
	path('consultation/', views.ConsultationView.as_view(), name='consultation'),
	path('mind_gym/', views.MindGymView.as_view(), name='mind_gym'),

	# Export MFA
	path('export_mfa/<int:pk>/', views.ExportMFA.as_view(), name='export_mfa'),

	## Library ##
	path('library/', views.LibraryView.as_view(), name='library'),	
	# Media
	path('library/media/tutorials', views.TutorialsView.as_view(), name='library_media_tutorials'),
	path('library/media/articles', views.ArticlesView.as_view(), name='library_media_articles'),
	path('library/media/worksheets', views.WorksheetsView.as_view(), name='library_media_worksheets'),
	path('library/media/audio', views.AudioView.as_view(), name='library_media_audio'),
	path('library/media/videos', views.VideosView.as_view(), name='library_media_videos'),
	# Topic
	path('library/topic/overall_mental', views.OverallMentalView.as_view(), name='library_topic_overall_mental'),
	path('library/topic/ideal_performance', views.IdealPerformanceView.as_view(), name='library_topic_ideal_performance'),
	path('library/topic/mindfullness_meditation', views.MindfullnessMeditationView.as_view(), name='library_topic_mindfullness_meditation'),
	path('library/topic/sleep_rest', views.SleepRestView.as_view(), name='library_topic_sleep_rest'),
	path('library/topic/healing_recovery', views.HealingRecoveryView.as_view(), name='library_topic_healing_recovery'),
	path('library/topic/managing_thoughts_feelings', views.ManagingThoughtsFeelingsView.as_view(), name='library_topic_managing_thoughts_feelings'),

	path('api/', include('home.api.urls'), name='api')
]

successinmind/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('home.urls')),

	path('api-auth/', include('rest_framework.urls'), name='rest_framework'),


	path('cn4/', include('cn4.urls'))
]

home/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('first_name', 'last_name', 'username', 'email', 'password')


class LoginForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('email', 'password')

home/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions

from home.api import serializers
from home import models

# For Teams
import random
import string


class ApiMainView(APIView):

	def get(self, response):
		return Response({
			'/api/mfa': ['GET - Returns all MFAs by User (Filterable by \'date\')'],
			'/api/journal': [
				'GET - Returns all Journals by User (Filterable by \'date\')',
				'POST - Creates new Journal record. Requires \'date\', \'text\'',
				'DELETE - Deletes Journal record of user. Requires \'date\'',
			],
			'/api/weekly_plan': [
				'GET - Returns all Weekly Plan by User (Filterable by \'date\')',
				'POST - Creates new Weekly Plan record. Requires \'date\', \'text\'',
				'DELETE - Deletes Weekly Plan record of user. Requires \'date\'',
			],
			'/api/mfa_team': [
				'GET - Returns a generated team code. If code is specified, returns \
				name of team with associated code.',
				'POST - Creates team with inputted code and name referenced to user.'
			]
			})



class UserApiView(APIView):

	def post(self, request, *args, **kwargs):
		data = {
			'username': request.data.get('email'),
			'email': request.data.get('email'),
			'first_name': request.data.get('first_name'),
			'last_name': request.data.get('last_name'),
			'password': request.data.get('password'),
		}
		sports = request.data.get('sports')
		gender = request.data.get('gender')
		serializer = serializers.JournalSerializer(data=data)
		if serializer.is_valid():
			user = serializer.save()
			
			profile = models.Profile(user=user)
			profile.sports = sports
			profile.gender = gender
			profile.save()

			return Response(serializer.data, status=status.HTTP_201_CREATED)
		else:
			return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class MFAApiView(APIView):
	permission_classes = [permissions.IsAuthenticated]

	def get(self, request, *args, **kwargs):
		date = request.data.get('date')
		if date:
			mfa = models.MentalFitnessAssessment.objects.filter(user=request.user, date=date)
		else:
			mfa = models.MentalFitnessAssessment.objects.filter(user=request.user)
		serializer = serializers.MentalFitnessAssessmentSerializer(mfa, many=True)

		return Response(serializer.data, status=status.HTTP_200_OK)


class JournalApiView(APIView):
	permission_classes = [permissions.IsAuthenticated]

	def get(self, request, *args, **kwargs):
		date = request.data.get('date', None)
		if date:
			journal = models.Journal.objects.filter(user=request.user, date=date)
		else:
			journal = models.Journal.objects.filter(user=request.user)
		serializer = serializers.JournalSerializer(journal, many=True)

		return Response(serializer.data, status=status.HTTP_200_OK)

	def post(self, request, *args, **kwargs):
		data = {
			'user': request.user.id,
			'date': request.data.get('date'),
			'training_goals': request.data.get('training_goals'),
			'mental_fitness_goals': request.data.get('mental_fitness_goals'),
			'course_work_goals': request.data.get('course_work_goals'),
			'awesome_performance': request.data.get('awesome_performance'),
			'great_practice': request.data.get('great_practice'),
			'feeling_happy': request.data.get('feeling_happy'),
			'feeling_confident': request.data.get('feeling_confident'),
			'good_rest': request.data.get('good_rest'),
			'confidence': request.data.get('confidence'),
			'concentration': request.data.get('concentration'),
			'composure': request.data.get('composure'),
			'challenge_response': request.data.get('challenge_response'),
			'commitment': request.data.get('commitment'),
			'overall_performance_rating': request.data.get('overall_performance_rating'),
			'overall_satisfaction_rating': request.data.get('overall_satisfaction_rating'),
		}
		serializer = serializers.JournalSerializer(data=data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		else:
			return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

	def delete(self, request, *args, **kwargs):
		data = {
			'user': request.user.id,
			'date': request.data.get('date')
		}

		journal = models.Journal.objects.filter(user=data['user'], date=data['date'])
		if journal:
			journal.delete()
			return Response(status=status.HTTP_200_OK)
		else:
			return Response(status=status.HTTP_400_BAD_REQUEST)




class WeeklyPlanApiView(APIView):
	permission_classes = [permissions.IsAuthenticated]

	def get(self, request, *args, **kwargs):
		date = request.data.get('date', None)
		if date:
			weekly_plan = models.WeeklyPlan.objects.filter(user=request.user, date=date)
		else:
			weekly_plan = models.WeeklyPlan.objects.filter(user=request.user)
		serializer = serializers.WeeklyPlanSerializer(weekly_plan, many=True)

		return Response(serializer.data, status=status.HTTP_200_OK)

	def post(self, request, *args, **kwargs):
		data = {
			'user': request.user.id,
			'date': request.data.get('date'),
			'vision': request.date.get('vision'),
			'training_goals': request.date.get('training_goals'),
			'mental_fitness_goals': request.date.get('mental_fitness_goals'),
			'course_work_goals': request.date.get('course_work_goals'),
			'recreational_goals': request.date.get('recreational_goals'),
			'goal_for_overall_performance_rating': request.date.get('goal_for_overall_performance_rating'),
			'goal_for_level_of_satisfaction': request.date.get('goal_for_level_of_satisfaction'),
		}
		serializer = serializers.WeeklyPlanSerializer(data=data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		else:
			return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

	def delete(self, request, *args, **kwargs):
		data = {
			'user': request.user.id,
			'date': request.data.get('date'),
		}

		weekly_plan = models.WeeklyPlan.objects.filter(user=data['user'], date=data['date'])
		if weekly_plan:
			weekly_plan.delete()
			return Response(status=status.HTTP_200_OK)
		else:
			return Response(status=status.HTTP_400_BAD_REQUEST)


class TeamMFAApiView(APIView):
	permission_classes = [permissions.IsAuthenticated]

	def get(self, request, *args, **kwargs):
		code = request.data.get('code', None)
		if not code:
			code = request.GET.get('code', None)
		data = {}
		if code:
			team = models.Team_MentalFitnessAssessment.objects.get(team_code=code)
			if team:
				data['name'] = team.name
			else:
				data['name'] = "Team not found"
		else:
			match = True
			while match:
				chars = string.ascii_uppercase + string.digits
				code = ''.join(random.choice(chars) for i in range(6))
				match = models.Team_MentalFitnessAssessment.objects.filter(team_code=code)
			data['code'] = code
		return Response(data, status=status.HTTP_200_OK)

	def post(self, request, *args, **kwargs):
		data = {
			'user': request.user.id,
			'code': request.data.get('code'),
			'name': request.data.get('name'),
		}
		serializer = serializers.TeamMentalFitnessAssessment(data=data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		else:
			return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

home/templates/MFA_team_select.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
	<link rel="stylesheet" href="{% static 'css/MFA_team_select.css'%}">
	<!-- Log In Block -->
	<div id='enclosure'>
		<h1>Team Mental Fitness Assessment</h1>
		<h4>Take your Mental Fitness Assessment as a Team</h4>
		<br>
		<form id='team_form' method='post'>
			{% csrf_token %}
			<label for="team_token">Enter The Team Code</label>
			<div id='team_token_div'>
				<input name='team_token' type="text" style="text-transform:uppercase"
					class="form-control" id="team_token" value="" maxlength="6" required>
				<h4 id='team_name'></h4>
			</div>
			<p id='status_message'></p>
			<div id='submit' class="btn btn-primary">Take Assessment</div>
			<script src="{% static 'js/team_select.js' %}"></script>
		</form>
	</div>
{% endblock %}

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<!-- Created, Deployed, and Designed by Maximilian Terenzi -->
{% load static %}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
	<!-- jquery -->
	<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
	<script src="{% static 'js/jquery.color-2.1.0.js' %}"></script>
	<!-- Base CSS -->
	<link rel="stylesheet" href="{% static 'css/base.css'%}">
	<link rel="shortcut icon" type="image/png" href="{% static 'images/brand.png' %}"/>
	<title>Success In Mind</title>
</head>

<body>
	<!-- Nav Bar Content -->
	<nav class="navbar navbar-expand-lg navbar-dark">
		<div class="container-fluid">
			<a class="navbar-brand" href="{% url 'home:index' %}"><img id='brand' src="{% static 'images/brand.png' %}" alt="Dr. B"></a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
				data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item dropdown">
						<a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button"
							data-bs-toggle="dropdown" aria-expanded="false">
							Mental Fitness Assessment
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
							<li><a class="dropdown-item" href="{% url 'home:MFA' %}">Individual</a></li>
							<li><a class="dropdown-item" href="{% url 'home:MFA_Team' %}">Teams</a></li>
						</ul>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'home:B_60' %}">Dr. B in 60 Video Series</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" aria-current="page" href="{% url 'home:library' %}">Resource Library</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" aria-current="page" href="{% url 'home:mind_gym' %}">Mind Gym</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" aria-current="page" href="{% url 'home:consultation' %}">Consultation</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'home:teams' %}">Workshops with Teams</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" aria-current="page" href="{% url 'home:about' %}">About Dr. B</a>
					</li>
				</ul>
				<ul id='divider' class="navbar-nav ml-auto">
					{% if not user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'home:login' %}">Log In</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'home:sign_up' %}">Sign Up</a>
						</li>
					{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'home:profile'%}">Welcome, {{ user.get_full_name }}</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'home:logout' %}">Sign Out</a>
						</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>
	<!-- End Nav Bar Content -->
	{% block body_block %}
	{% endblock %}
</body>

</html>

home/templates/consultation.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
	<link rel="stylesheet" href="{% static 'css/consultation.css' %}">
	<div id='enclosure'>
		<div id='banner'>
			<h1>Stony Brook University</h1>
			<h2>Sport Psychology Services</h2>
		</div>
		<h4>Athletes can schedule individual session with Sport Psychologist and Certified Mental Performance Consultant</h4>
		<h3>Dr. Jack Bowman</h3>
		<h2>To Help You Develop:</h2>
		<div id='points_enclosure'>
			<div id='points'>
				<ul>
					<li>Improved Focus and Concentration</li>
					<li>Stronger Stress Management Skills</li>
					<li>More Effective Emotional Self-Regulation</li>
					<li>Increased Confidence</li>
					<li>Resiliency and Mental Toughness</li>
				</ul>
			</div>
		</div>
		<h4>Appointments scheduled through your Athletic Trainer</h4>
	</div>
{% endblock %}

home/templates/library.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'css/library.css' %}">
<div id='enclosure'>
	<h1>Success In Mind Library</h1>
	<p>The Resource Library contains narrated tutorials, articles, worksheets, audio downloads, and videos to strengthen
		your Mental
		Fitness and assist you in the pursuit of EXCELLENCE on the Pathway to Success.
	</p>
	<p>It can be used in two ways. First, by browsing its contents in search of a specific educational tool you can use
		to practice a Mental Training routine.
		Its second and highly effective utility is as a companion to the <a href="{% url 'home:MFA' %}">Mental Fitness
			Assessment</a> and the
		accompanying <a href="{% url 'home:mind_gym' %}">Mind Gym</a> mental workouts.
	</p>
	<br><br>
	<div class='row'>
		<div class='col-sm-6'>
			<h5>Links - (Ordered By Media Format)</h5>
			<ul id='media' class='centered-list'>
				<li><a href="{% url 'home:library_media_tutorials' %}">Narrated Tutorials</a></li>
				<li><a href="{% url 'home:library_media_articles' %}">Articles</a></li>
				<li><a href="{% url 'home:library_media_worksheets' %}">Worksheets</a></li>
				<li><a href="{% url 'home:library_media_audio' %}">Audio Downloads</a></li>
				<li><a href="{% url 'home:library_media_videos' %}">Videos</a></li>
			</ul>
		</div>
		<div class='col-sm-6'>
			<h5>Links - (Ordered By Topic)</h5>
			<ul id='topic' class='centered-list'>
				<li><a href="{% url 'home:library_topic_overall_mental' %}">Overall Mental Fitness</a></li>
				<li><a href="{% url 'home:library_topic_ideal_performance' %}">Ideal Performance State and Flow</a></li>
				<li><a href="{% url 'home:library_topic_mindfullness_meditation' %}">Mindfulness and Meditation</a></li>
				<li><a href="{% url 'home:library_topic_sleep_rest' %}">Sleep and Rest</a></li>
				<li><a href="{% url 'home:library_topic_healing_recovery' %}">Healing and Recovery</a></li>
				<li><a href="{% url 'home:library_topic_managing_thoughts_feelings' %}">Managing Thoughts and Feelings</a></li>
			</ul>
		</div>
	</div>
</div>
{% endblock %}

home/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
	<link rel="stylesheet" href="{% static 'css/login.css'%}">
	<!-- Log In Block -->
	<div id='enclosure'>
		<h1>Log In</h1><br>
		<form method='post'>
			{% csrf_token %}
			<div class="form-group">
				<label for="exampleInputEmail1">Email address</label>
				<input name='email' type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
					placeholder="Enter email">
			</div><br>
			<div class="form-group">
				<label for="password">Password</label>
				<input name='password' type="password" class="form-control" id="password" placeholder="Password">
			</div>
			{% if failed %}
				<br>
				<p style="color:red">Login Failed! Check email and password and try again.</p>
			{% endif %}
			<br>
			<div id='button'>
				<button type="submit" class="btn btn-primary">Submit</button>
			</div>
		</form>
	</div>
	<br>
	<p id='account'>Don't have an account? <a href="{% url 'home:sign_up' %}">Sign Up</a></p>
{% endblock %}

home/templates/profile.html
{% extends 'base.html' %}

{% load static %}
{% block body_block %}
	<link rel="stylesheet" href="{% static 'css/profile.css' %}">
	<div id='outer'>
		{% if coach %}
			<h1>Coach Profile</h1>
		{% else %}
			<h1>Athlete Profile</h1>
		{% endif %}
		<br>
		<div id='inner'>
			<h3>{{ user.get_full_name }},</h3><br>
			<h5>Info:</h5>
			<p>&emsp;Email: {{ user.email }}</p>
			<p>&emsp;Sport: {{ profile.sports }}</p>
			<br>
			<!-- Team Mental Fitness Table -->
			{% if coach %}
				<div id='team_header' class='row align-items-center'>
					<h4 class='col-md-8'>Team Mental Fitness Assessments</h4>
					<div class='col-md-4'>
						<button id='create_team' type="submit" class="btn btn-primary">Create a Team</button>
					</div>
				</div>
				{% if teams %}
					<div class='table-responsive'>
						<table class='table table-striped'>
							<thead class='table-dark'>
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Code</th>
									<th>Submissions</th>
									<th>Confidence</th>
									<th>Concentration</th>
									<th>Composure</th>
									<th>Challenge</th>
									<th>Commitment</th>
									<th>Overall Level</th>
								</tr>
							</thead>
							<tbody>
								{% for team in teams %}
									<tr>
										<th>{{ forloop.counter }}</th>
										<td>{{team.name}}</td>
										<td>{{team.code}}</td>
										<td>{{team.submissions}}</td>
										<td>{{team.a_confidence|floatformat:2}}%</td>
										<td>{{team.a_concentration|floatformat:2}}%</td>
										<td>{{team.a_composure|floatformat:2}}%</td>
										<td>{{team.a_challenge|floatformat:2}}%</td>
										<td>{{team.a_commitment|floatformat:2}}%</td>
										<td>{{team.a_total|floatformat:2}}%</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				{% else %}
					<td><p>Nothing here yet! Create a Team</p></td>
				{% endif %}
				<br>
			{% endif %}
			<!-- Mental Fitness Table -->
			{% if coach %}
				<h4>Individual Mental Fitness Assessments</h4>
			{% else %}
				<h4>Mental Fitness Assessments</h4>
			{% endif %}
			{% if MFAs %}
				<div class='table-responsive'>
					<table class='table table-striped'>
						<thead class='table-dark'>
							<tr>
								<th>#</th>
								<th>Date</th>
								<th>Confidence</th>
								<th>Concentration</th>
								<th>Composure</th>
								<th>Challenge</th>
								<th>Commitment</th>
								<th>Overall Level</th>
								<th>Export</th>
							</tr>
						</thead>
						<tbody>
							{% for MFA in MFAs %}
								<tr>
									<th>{{ forloop.counter }}</th>
									<td>{{MFA.date|date:'n/j/Y'}} - {{MFA.date|time:'g:i a'}}</td>
									<td>{{MFA.o_confidence|floatformat:2}}%</td>
									<td>{{MFA.o_concentration|floatformat:2}}%</td>
									<td>{{MFA.o_composure|floatformat:2}}%</td>
									<td>{{MFA.o_challenge|floatformat:2}}%</td>
									<td>{{MFA.o_commitment|floatformat:2}}%</td>
									<td>{{MFA.total|floatformat:2}}%</td>
									<td>
										<a href="{% url 'home:export_mfa' pk=MFA.pk %}" target="_blank">
											<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
											<path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
											<path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
											</svg>
										</a>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			{% else %}
				<td>Nothing here yet! Complete a Mental Fitness Assessment</td>
				<br>
			{% endif %}
			<!-- End Mental Fitness Table -->
			</div>
	</div>

	{% if coach %}
		<div id='team_creator' style="visibility: hidden;">
			<svg id='close_team' xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
				<path d="M1.293 1.293a1 1 0 0 1 1.414 0L8 6.586l5.293-5.293a1 1 0 1 1 1.414 1.414L9.414 8l5.293 5.293a1 1 0 0 1-1.414 1.414L8 9.414l-5.293 5.293a1 1 0 0 1-1.414-1.414L6.586 8 1.293 2.707a1 1 0 0 1 0-1.414z"/>
			</svg>
			<form id='team_form' method='post'>
				{% csrf_token %}
				<h1>Create a Team</h1>
				<label for="password">Name the Team</label>
				<input name='team_name' type="text" class="form-control" id="team_name" placeholder="Name" maxlength="128" required>
				<br>
				<div id='refresh_button' class="btn btn-primary">
					<svg id='refresh' xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-repeat" viewBox="0 0 16 16">
						<path d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41zm-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9z"/>
						<path fill-rule="evenodd" d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5.002 5.002 0 0 0 8 3zM3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9H3.1z"/>
					</svg>
				</div>
				<div id='team_token_div'>
					<div id='copy_div'>
						<svg id='copy' xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16">
							<path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
							<path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
						</svg>
					</div>
					<input name='team_token' type="text" class="form-control" id="team_token" value="XXXXXX" readonly>
				</div>
				<p id='status_message'></p>
				<div id='submit' class="btn btn-primary">Create</div>
			</form>
		</div>
		<script src="{% static 'js/profile_coach.js' %}"></script>
	{% endif %}

{% endblock %}